{
    'total_results': 10,
    'page': 1,
    'per_page': 10,
    'results': [
        {
            'count': 231,
            'month_of_year': {
                1: 0,
                2: 0,
                3: 0,
                4: 1,
                5: 21,
                6: 38,
                7: 33,
                8: 47,
                9: 62,
                10: 29,
                11: 0,
                12: 0,
            },
            'controlled_attribute': {
                'id': 1,
                'ontology_uri': '',
                'uri': '',
                'is_value': False,
                'multivalued': False,
                'uuid': 'f895e9ce-fb2d-4a63-a486-ac424f497e02',
                'values': [
                    {
                        'id': 2,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '48722062-360d-4b6e-b72c-129c7066b3fa',
                        'taxon_ids': [1],
                        'label': 'Adult',
                    },
                    {
                        'id': 3,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': 'b3b6e6d0-cbce-4886-bb2b-55bd99d44586',
                        'taxon_ids': [47792, 50190],
                        'label': 'Teneral',
                    },
                    {
                        'id': 4,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': 'c883d7b5-4eb5-4ad1-8cbc-56f5e2555869',
                        'taxon_ids': [
                            47208,
                            48763,
                            49369,
                            47157,
                            47822,
                            47201,
                            62164,
                            47864,
                            83204,
                            83202,
                            47794,
                        ],
                        'label': 'Pupa',
                    },
                    {
                        'id': 5,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '0f0c03c2-4741-46db-a19a-7cac8a96d667',
                        'taxon_ids': [
                            47793,
                            81769,
                            56834,
                            47744,
                            47792,
                            47651,
                            47504,
                            48011,
                            48112,
                            53795,
                            47198,
                            83187,
                            83201,
                            83200,
                        ],
                        'label': 'Nymph',
                    },
                    {
                        'id': 6,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '8ff477bd-0949-4a7a-9c67-64a8e3786876',
                        'taxon_ids': [
                            20978,
                            47208,
                            47822,
                            47201,
                            47157,
                            49369,
                            47864,
                            48763,
                            47794,
                            83204,
                            83202,
                            62164,
                        ],
                        'label': 'Larva',
                    },
                    {
                        'id': 7,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': 'fe58aedb-4375-4096-a61f-1cd718cf319f',
                        'taxon_ids': [
                            43233,
                            47120,
                            85497,
                            47178,
                            20978,
                            3,
                            49231,
                            47273,
                            60450,
                            49099,
                            26036,
                            47115,
                        ],
                        'label': 'Egg',
                    },
                    {
                        'id': 8,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '3245d167-ffff-44ce-a366-cfc8f711d73f',
                        'taxon_ids': [1],
                        'excepted_taxon_ids': [184884],
                        'label': 'Juvenile',
                    },
                    {
                        'id': 16,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '6ff4f9f8-7bc0-4d50-bee5-7072d11a04ef',
                        'taxon_ids': [48011],
                        'label': 'Subimago',
                    },
                ],
                'taxon_ids': [1],
                'excepted_taxon_ids': [43583],
                'label': 'Life Stage',
            },
            'controlled_value': {
                'id': 2,
                'ontology_uri': '',
                'uri': '',
                'is_value': True,
                'blocking': False,
                'taxon_ids': [1],
                'label': 'Adult',
                'values': [],
            },
        },
        {
            'count': 150,
            'month_of_year': {
                1: 0,
                2: 0,
                3: 0,
                4: 0,
                5: 0,
                6: 59,
                7: 27,
                8: 40,
                9: 24,
                10: 0,
                11: 0,
                12: 0,
            },
            'controlled_attribute': {
                'id': 1,
                'ontology_uri': '',
                'uri': '',
                'is_value': False,
                'multivalued': False,
                'uuid': 'f895e9ce-fb2d-4a63-a486-ac424f497e02',
                'values': [
                    {
                        'id': 2,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '48722062-360d-4b6e-b72c-129c7066b3fa',
                        'taxon_ids': [1],
                        'label': 'Adult',
                    },
                    {
                        'id': 3,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': 'b3b6e6d0-cbce-4886-bb2b-55bd99d44586',
                        'taxon_ids': [47792, 50190],
                        'label': 'Teneral',
                    },
                    {
                        'id': 4,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': 'c883d7b5-4eb5-4ad1-8cbc-56f5e2555869',
                        'taxon_ids': [
                            47208,
                            48763,
                            49369,
                            47157,
                            47822,
                            47201,
                            62164,
                            47864,
                            83204,
                            83202,
                            47794,
                        ],
                        'label': 'Pupa',
                    },
                    {
                        'id': 5,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '0f0c03c2-4741-46db-a19a-7cac8a96d667',
                        'taxon_ids': [
                            47793,
                            81769,
                            56834,
                            47744,
                            47792,
                            47651,
                            47504,
                            48011,
                            48112,
                            53795,
                            47198,
                            83187,
                            83201,
                            83200,
                        ],
                        'label': 'Nymph',
                    },
                    {
                        'id': 6,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '8ff477bd-0949-4a7a-9c67-64a8e3786876',
                        'taxon_ids': [
                            20978,
                            47208,
                            47822,
                            47201,
                            47157,
                            49369,
                            47864,
                            48763,
                            47794,
                            83204,
                            83202,
                            62164,
                        ],
                        'label': 'Larva',
                    },
                    {
                        'id': 7,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': 'fe58aedb-4375-4096-a61f-1cd718cf319f',
                        'taxon_ids': [
                            43233,
                            47120,
                            85497,
                            47178,
                            20978,
                            3,
                            49231,
                            47273,
                            60450,
                            49099,
                            26036,
                            47115,
                        ],
                        'label': 'Egg',
                    },
                    {
                        'id': 8,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '3245d167-ffff-44ce-a366-cfc8f711d73f',
                        'taxon_ids': [1],
                        'excepted_taxon_ids': [184884],
                        'label': 'Juvenile',
                    },
                    {
                        'id': 16,
                        'ontology_uri': '',
                        'uri': '',
                        'blocking': False,
                        'uuid': '6ff4f9f8-7bc0-4d50-bee5-7072d11a04ef',
                        'taxon_ids': [48011],
                        'label': 'Subimago',
                    },
                ],
                'taxon_ids': [1],
                'excepted_taxon_ids': [43583],
                'label': 'Life Stage',
            },
            'controlled_value': {
                'id': 6,
                'ontology_uri': '',
                'uri': '',
                'is_value': True,
                'blocking': False,
                'taxon_ids': [
                    20978,
                    47208,
                    47822,
                    47201,
                    47157,
                    49369,
                    47864,
                    48763,
                    47794,
                    83204,
                    83202,
                    62164,
                ],
                'label': 'Larva',
                'values': [],
            },
        },
    ],
}
