from datetime import datetime

from dateutil.tz import tzoffset

{
    "total_results": 1,
    "page": 1,
    "per_page": 1,
    "results": [
        {
            'id': 16227955,
            'annotations': [
                {
                    'concatenated_attr_val': '1|2',
                    'controlled_attribute_id': 1,
                    'controlled_value_id': 2,
                    'user': {
                        'activity_count': 1184,
                        'created_at': '2018-04-23T17:11:14+00:00',
                        'icon': 'https://static.inaturalist.org/attachments/users/icons/886482/thumb.jpg?1529671435',
                        'icon_url': 'https://static.inaturalist.org/attachments/users/icons/886482/medium.jpg?1529671435',
                        'id': 886482,
                        'identifications_count': 120,
                        'journal_posts_count': 0,
                        'login': 'niconoe',
                        'login_autocomplete': 'niconoe',
                        'login_exact': 'niconoe',
                        'name': 'Nicolas Noé',
                        'name_autocomplete': 'Nicolas Noé',
                        'observations_count': 1064,
                        'orcid': 'https://orcid.org/0000-0002-9503-4750',
                        'roles': [],
                        'site_id': 1,
                        'spam': False,
                        'species_count': 471,
                        'suspended': False,
                        'universal_search_rank': 1064,
                    },
                    'user_id': 886482,
                    'uuid': '14bbd34f-73f8-4b99-b591-8517913788a1',
                    'vote_score': 0,
                    'votes': [],
                }
            ],
            'cached_votes_total': 0,
            'captive': False,
            'comments': [
                {
                    'body': 'suspect L. bardanae - but sits on Solanum (non-host)',
                    'created_at': '2018-09-05T14:08:09+00:00',
                    'created_at_details': {
                        'date': '2018-09-05',
                        'day': 5,
                        'hour': 14,
                        'month': 9,
                        'week': 36,
                        'year': 2018,
                    },
                    'flags': [],
                    'hidden': False,
                    'id': 2071611,
                    'moderator_actions': [],
                    'user': {
                        'activity_count': 503804,
                        'created_at': '2016-02-18T10:19:19+00:00',
                        'icon': None,
                        'icon_url': None,
                        'id': 180811,
                        'identifications_count': 503804,
                        'journal_posts_count': 0,
                        'login': 'borisb',
                        'login_autocomplete': 'borisb',
                        'login_exact': 'borisb',
                        'name': '',
                        'name_autocomplete': '',
                        'observations_count': 0,
                        'orcid': None,
                        'roles': ['curator'],
                        'site_id': 1,
                        'spam': False,
                        'species_count': 0,
                        'suspended': False,
                        'universal_search_rank': 0,
                    },
                    'uuid': 'e6fc62ea-e22b-4427-bb65-1ba3bc591c77',
                },
                {
                    'body': 'I now see: Bonus species on observation! You may make '
                    'a duplicate . . . \n'
                    '(Flea beetle Epitrix pubescens on Solanum bud) \n',
                    'created_at': '2018-09-05T16:03:40+00:00',
                    'created_at_details': {
                        'date': '2018-09-05',
                        'day': 5,
                        'hour': 16,
                        'month': 9,
                        'week': 36,
                        'year': 2018,
                    },
                    'flags': [],
                    'hidden': False,
                    'id': 2071896,
                    'moderator_actions': [],
                    'user': {
                        'activity_count': 503804,
                        'created_at': '2016-02-18T10:19:19+00:00',
                        'icon': None,
                        'icon_url': None,
                        'id': 180811,
                        'identifications_count': 503804,
                        'journal_posts_count': 0,
                        'login': 'borisb',
                        'login_autocomplete': 'borisb',
                        'login_exact': 'borisb',
                        'name': '',
                        'name_autocomplete': '',
                        'observations_count': 0,
                        'orcid': None,
                        'roles': ['curator'],
                        'site_id': 1,
                        'spam': False,
                        'species_count': 0,
                        'suspended': False,
                        'universal_search_rank': 0,
                    },
                    'uuid': '4d401d20-1b08-464a-8287-351f5b57443e',
                },
            ],
            'comments_count': 2,
            'community_taxon_id': 493595,
            'created_at': datetime(2018, 9, 5, 14, 31, 8, tzinfo=tzoffset(None, 7200)),
            'created_at_details': {
                'date': '2018-09-05',
                'day': 5,
                'hour': 14,
                'month': 9,
                'week': 36,
                'year': 2018,
            },
            'created_time_zone': 'Europe/Paris',
            'description': '',
            'faves': [],
            'faves_count': 0,
            'flags': [],
            'geojson': {'coordinates': [4.360086, 50.646894], 'type': 'Point'},
            'geoprivacy': None,
            'ident_taxon_ids': [
                48460,
                1,
                47120,
                372739,
                47158,
                184884,
                47208,
                71130,
                372852,
                60473,
                48736,
                272543,
                507383,
                71157,
                1101667,
                493595,
            ],
            'identifications': 'TRUNCATED',
            'identifications_count': 2,
            'identifications_most_agree': True,
            'identifications_most_disagree': False,
            'identifications_some_agree': True,
            'license_code': 'cc0',
            'location': [50.646894, 4.360086],
            'map_scale': 17,
            'mappable': True,
            'non_owner_ids': 'TRUNCATED',
            'num_identification_agreements': 2,
            'num_identification_disagreements': 0,
            'oauth_application_id': None,
            'obscured': False,
            'observation_photos': [
                {
                    'id': 22080796,
                    'photo': {
                        'attribution': '(c) Nicolas Noé, some ' 'rights reserved (CC BY)',
                        'flags': [],
                        'id': 24355315,
                        'license_code': 'cc-by',
                        'original_dimensions': {'height': 1057, 'width': 1445},
                        'url': 'https://inaturalist-open-data.s3.amazonaws.com/photos/24355315/square.jpeg',
                    },
                    'position': 0,
                    'uuid': '76b54495-3497-4e96-b07c-7ad346939a02',
                },
                {
                    'id': 22080797,
                    'photo': {
                        'attribution': '(c) Nicolas Noé, some ' 'rights reserved (CC BY)',
                        'flags': [],
                        'id': 24355313,
                        'license_code': 'cc-by',
                        'original_dimensions': {'height': 1364, 'width': 2048},
                        'url': 'https://inaturalist-open-data.s3.amazonaws.com/photos/24355313/square.jpeg',
                    },
                    'position': 1,
                    'uuid': '06b90a88-d98d-4447-b14c-5d354d2d68d1',
                },
            ],
            'observed_on': datetime(2018, 9, 5, 14, 6, tzinfo=tzoffset(None, 7200)),
            'observed_on_details': {
                'date': '2018-09-05',
                'day': 5,
                'hour': 14,
                'month': 9,
                'week': 36,
                'year': 2018,
            },
            'observed_on_string': '2018/09/05 2:06 PM CEST',
            'observed_time_zone': 'Europe/Paris',
            'ofvs': [],
            'outlinks': [{'source': 'GBIF', 'url': 'http://www.gbif.org/occurrence/1914197587'}],
            'owners_identification_from_vision': True,
            'photos': [
                {
                    'attribution': '(c) Nicolas Noé, some rights reserved (CC BY)',
                    'flags': [],
                    'id': 24355315,
                    'license_code': 'cc-by',
                    'original_dimensions': {'height': 1057, 'width': 1445},
                    'url': 'https://inaturalist-open-data.s3.amazonaws.com/photos/24355315/square.jpeg',
                },
                {
                    'attribution': '(c) Nicolas Noé, some rights reserved (CC BY)',
                    'flags': [],
                    'id': 24355313,
                    'license_code': 'cc-by',
                    'original_dimensions': {'height': 1364, 'width': 2048},
                    'url': 'https://inaturalist-open-data.s3.amazonaws.com/photos/24355313/square.jpeg',
                },
            ],
            'place_guess': '54 rue des Badauds',
            'place_ids': [
                7008,
                8657,
                14999,
                59614,
                67952,
                80627,
                81490,
                96372,
                96794,
                97391,
                97582,
                108692,
            ],
            'positional_accuracy': 23,
            'preferences': {'prefers_community_taxon': None},
            'project_ids': [],
            'project_ids_with_curator_id': [],
            'project_ids_without_curator_id': [],
            'project_observations': [],
            'public_positional_accuracy': 23,
            'quality_grade': 'research',
            'quality_metrics': [],
            'reviewed_by': [180811, 886482, 1226913],
            'site_id': 1,
            'sounds': [],
            'spam': False,
            'species_guess': 'Lixus bardanae',
            'tags': [],
            'taxon': {
                'ancestor_ids': [
                    48460,
                    1,
                    47120,
                    372739,
                    47158,
                    184884,
                    47208,
                    71130,
                    372852,
                    60473,
                    48736,
                    272543,
                    507383,
                    71157,
                    1101667,
                    493595,
                ],
                'ancestry': '48460/1/47120/372739/47158/184884/47208/71130/372852/60473/48736/272543/507383/71157/1101667',
                'atlas_id': None,
                'complete_species_count': None,
                'created_at': '2016-04-25T22:35:20+00:00',
                'current_synonymous_taxon_ids': None,
                'default_photo': {
                    'attribution': '(c) Andy Van de Velde, all rights '
                    'reserved, uploaded by Andy Van de '
                    'Velde',
                    'flags': [],
                    'id': 69087254,
                    'license_code': None,
                    'medium_url': 'https://static.inaturalist.org/photos/69087254/medium.jpg',
                    'original_dimensions': {'height': 1638, 'width': 2048},
                    'square_url': 'https://static.inaturalist.org/photos/69087254/square.jpg',
                    'url': 'https://static.inaturalist.org/photos/69087254/square.jpg',
                },
                'endemic': False,
                'extinct': False,
                'flag_counts': {'resolved': 0, 'unresolved': 0},
                'iconic_taxon_id': 47158,
                'iconic_taxon_name': 'Insecta',
                'id': 493595,
                'introduced': False,
                'is_active': True,
                'min_species_ancestry': '48460,1,47120,372739,47158,184884,47208,71130,372852,60473,48736,272543,507383,71157,1101667,493595',
                'min_species_taxon_id': 493595,
                'name': 'Lixus bardanae',
                'native': False,
                'observations_count': 86,
                'parent_id': 1101667,
                'photos_locked': False,
                'rank': 'species',
                'rank_level': 10,
                'taxon_changes_count': 0,
                'taxon_schemes_count': 1,
                'threatened': False,
                'universal_search_rank': 86,
                'wikipedia_url': None,
            },
            'taxon_geoprivacy': None,
            'time_zone_offset': '+01:00',
            'updated_at': datetime(2018, 9, 22, 19, 19, 27, tzinfo=tzoffset(None, 7200)),
            'uri': 'https://www.inaturalist.org/observations/16227955',
            'user': {
                'activity_count': 1184,
                'created_at': '2018-04-23T17:11:14+00:00',
                'icon': 'https://static.inaturalist.org/attachments/users/icons/886482/thumb.jpg?1529671435',
                'icon_url': 'https://static.inaturalist.org/attachments/users/icons/886482/medium.jpg?1529671435',
                'id': 886482,
                'identifications_count': 120,
                'journal_posts_count': 0,
                'login': 'niconoe',
                'login_autocomplete': 'niconoe',
                'login_exact': 'niconoe',
                'name': 'Nicolas Noé',
                'name_autocomplete': 'Nicolas Noé',
                'observations_count': 1064,
                'orcid': 'https://orcid.org/0000-0002-9503-4750',
                'preferences': {},
                'roles': [],
                'site_id': 1,
                'spam': False,
                'species_count': 471,
                'suspended': False,
                'universal_search_rank': 1064,
            },
            'uuid': '6448d03a-7f9a-4099-86aa-ca09a7740b00',
            'votes': [],
        },
    ],
}
