# Auto-generated enum parameter values from OpenAPI spec

# Params with the same allowed values across all endpoints
CONSTANT_ENUM_PARAMS = {
    'acc': ['true', 'false'],
    'active': ['true', 'false'],
    'agree': ['true', 'false'],
    'captive': ['true', 'false'],
    'client': ['inat-ios', 'inat-android', 'seek', 'inatrn'],
    'community': ['true', 'false'],
    'coords_viewable_for_proj': ['true', 'false'],
    'date_field': ['observed', 'created'],
    'disagreements': ['true', 'false'],
    'endemic': ['true', 'false'],
    'expected_nearby': ['true', 'false'],
    'fails_dqa_accurate': ['true', 'false'],
    'fails_dqa_date': ['true', 'false'],
    'fails_dqa_evidence': ['true', 'false'],
    'fails_dqa_location': ['true', 'false'],
    'fails_dqa_needs_id': ['true', 'false'],
    'fails_dqa_recent': ['true', 'false'],
    'fails_dqa_subject': ['true', 'false'],
    'fails_dqa_wild': ['true', 'false'],
    'features': ['true', 'false'],
    'following': ['yes', 'no', 'any'],
    'geo': ['true', 'false'],
    'has_params': ['true', 'false'],
    'has_posts': ['true', 'false'],
    'iconic': ['true', 'false'],
    'id_please': ['true', 'false'],
    'identifications': ['most_agree', 'most_disagree', 'some_agree'],
    'identified': ['true', 'false'],
    'include_ancestors': ['true', 'false'],
    'include_suspended': ['true', 'false'],
    'include_taxon_ancestors': ['true', 'false'],
    'introduced': ['true', 'false'],
    'is_active': ['true', 'false'],
    'licensed': ['true', 'false'],
    'mappable': ['true', 'false'],
    'metric': ['date', 'evidence', 'location', 'needs_id', 'recent', 'wild', 'subject', 'accurate'],
    'native': ['true', 'false'],
    'no_histograms': ['true', 'false'],
    'noteworthy': ['true', 'false'],
    'observations_by': ['owner', 'following'],
    'only_id': ['true', 'false'],
    'order': ['desc', 'asc'],
    'out_of_range': ['true', 'false'],
    'pcid': ['true', 'false'],
    'photo_licensed': ['true', 'false'],
    'photos': ['true', 'false'],
    'placement': ['users/dashboard#sidebar', 'users/dashboard', 'welcome/index', 'mobile/home', 'mobile'],
    'popular': ['true', 'false'],
    'prefers_hide_obs_show_identifiers': ['true', 'false'],
    'reviewed': ['true', 'false'],
    'rule_details': ['true', 'false'],
    'search_on': ['names', 'tags', 'description', 'place', 'taxon_page_obs_photos'],
    'skip_counts': ['true', 'false'],
    'sounds': ['true', 'false'],
    'source': ['captive_observations', 'checklist', 'misidentifications', 'observations', 'rg_observations', 'visual'],
    'taxon_is_active': ['true', 'false'],
    'threatened': ['true', 'false'],
    'thresholded': ['true', 'false'],
    'tile_size': [256, 512],
    'trusted': ['yes', 'no', 'any'],
    'unannotated': ['true', 'false'],
    'verifiable': ['true', 'false'],
    'viewed': ['true', 'false'],
}

# Params with different allowed values depending on the endpoint
VARIABLE_ENUM_PARAMS = {
    'interval': {
        '/observations/histogram': ['year', 'month', 'week', 'day', 'hour', 'month_of_year', 'week_of_year'],
        '/observations/popular_field_values': ['month_of_year', 'week_of_year'],
        '/places/nearby': ['year', 'month', 'week', 'day', 'hour', 'month_of_year', 'week_of_year'],
    },
    'order_by': {
        '/grid/{zoom}/{x}/{y}.grid.json': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/grid/{zoom}/{x}/{y}.png': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/heatmap/{zoom}/{x}/{y}.png': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/observations': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/observations/histogram': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/observations/iconic_taxa_species_counts': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/observations/identifiers': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/observations/observers': ['observation_count', 'species_count'],
        '/observations/popular_field_values': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/observations/umbrella_project_stats': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/places': ['area'],
        '/places/nearby': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/places/{id}/{zoom}/{x}/{y}.png': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/places/{uuid}': ['admin_and_distance'],
        '/points/{zoom}/{x}/{y}.grid.json': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/points/{zoom}/{x}/{y}.png': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/projects': ['recent_posts', 'created', 'updated', 'distance', 'featured'],
        '/projects/{id}/members': ['observations_count', 'login'],
        '/relationships': ['friendships.id', 'users.login'],
        '/taxa/suggest': ['taxonomy', 'default', 'sciname'],
        '/taxon_id_summaries': ['run_generated_at', 'created_at', 'updated_at', 'taxon_id'],
        '/taxon_places/{id}/{zoom}/{x}/{y}.png': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
        '/taxon_ranges/{id}/{zoom}/{x}/{y}.png': ['created_at', 'geo_score', 'id', 'observed_on', 'random', 'species_guess', 'updated_at', 'votes'],
    },
}
